MacLinux/README.txt, MacLinux/rules/createRule, MacLinux/rules/ruleCode/rule_code.py, MacLinux/rules/ruleCode/rule_util.py, MacLinux/setup/setup, Windows/README.txt, Windows/rules/createRule.cmd, Windows/rules/ruleCode/rule_code.py, Windows/rules/ruleCode/rule_util.py
Add Profile to Windows + Setup turn on Config + Documentation
=> New features and fixes

MacLinux/rules/ruleCode/python/rule_util.py
Sorry, some ^M substitutions happened when saved on my Mac.  Primarily changes are lines 71-73.
=> default ruleParameters to {} and override only if present in the event

rdk/rdk.py
=> Fix for deploy command including previous zips in new S3 package

rdk/template/runtime/python3.6/rule_code.py
Modified functions to facilitate using roles for cross account and managed rule
Clean up code following pylint
Added 2 functions to build evaluations with annotation.
=> Clean up code and add role handling

rdk/rdk.py, rdk/template/runtime/python3.6/rule_code.py
Bug fix when update with a rule name with underscores.
=> Bug stackname when update

rdk/template/runtime/python3.6/rule_code.py
Ability to return dict in order to avoid to have to build a list for single custom evaluations
=> Add ability to return dict on evaluate_compliance()

rdk/rdk.py, setup.py, testing/test_windows.sh
=> Adding the ability to include Managed Rules in generated CFN templates

rdk/template/runtime/python3.6/rule_code.py, rdk/template/runtime/python3.6/rule_test.py
Correct the base template as it fails if periodic
=> correct base template handling

bin/rdk, rdk/rdk.py
This also touched the __wait_for_cfn_stack() method, and so I took the opportunity to add some more sophisticated error handling.
=> Added 'undeploy' command

rdk/template/runtime/python3.6/rule_code.py
=> add the loop in template

rdk/template/runtime/python3.6/rule_code.py, rdk/template/runtime/python3.6/rule_test.py
=> Update on template

rdk/rdk.py
*Issue #148*
*Adds missing {"Fn::Sub"}*
=> Fix for missing sub for ${AWS::Partition}

MANIFEST.in, README.rst, docs/getting_started.rst, docs/reference/test-local.rst, rdk/__init__.py, rdk/rdk.py, rdk/template/runtime/python3.7/rule_code.py, rdk/template/runtime/python3.7/rule_test.py, testing/linux-python2-buildspec.yaml, testing/linux-python3-buildspec.yaml, testing/test_windows.sh
*Issue #, if available:* #151
*Description of changes:* The goal of this pull request is to add support for the Python 3.7 AWS Lambda run time.
=> Add support for Python 3.7

rdk/rdk.py, rdk/template/configRule.json
=> rdklib multi-region support

rdk/template/example_ci/AWS_LAMBDA_FUNCTION.json
=> Added sample ci for Lambda function.

rdk/template/example_ci/AWS_ELASTICLOADBALANCING_LOADBALANCER.json, rdk/template/example_ci/AWS_LAMBDA_FUNCTION.json
=> Sample CI for ELB

rdk/template/runtime/python3.6-lib/rule_test.py
=> Updating template to match 3.6

rdk/template/runtime/python3.6-lib/rule_code.py, rdk/template/runtime/python3.6-lib/rule_test.py
=> update rdklib template

rdk/rdk.py, rdk/template/example_ci/AWS_ELASTICLOADBALANCING_LOADBALANCER.json, rdk/template/example_ci/AWS_LAMBDA_FUNCTION.json
=> Update rdklib layer version mapping

rdk/template/runtime/python3.6-lib/rule_test.py
=> correct the import of module in test_code for the rdklib

rdk/__init__.py, rdk/rdk.py, rdk/template/configRule.json, rdk/template/runtime/python3.6/rule_code.py, rdk/template/runtime/python3.7/rule_code.py
=> Adding execution role arn detection and arbitrary lambda layer support

rdk/template/example_ci/AWS_IAM_User.json, rdk/template/runtime/python3.6-lib/rule_test.py
=> correct IAM User sample

rdk/__init__.py, rdk/rdk.py
=> Fixing other merge conflict.

rdk/rdk.py
N/A
Updated and sorted list of accepted resource types from https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html
=> Update accepted resource types

docs/reference/deploy.rst, rdk/__init__.py
Bumping point release version number for pypi upload, and also fixing a typo in the documentation.
=> Bumping version for pypi upload

.gitignore, rdk/__init__.py, rdk/rdk.py, rdk/template/configManagedRuleWithRemediation.json
=> Bumping version for pypi upload and fixes after code review

rdk-workshop/WorkshopSetup.yaml, rdk-workshop/instructions.md
Based on the request for the RDK workshop, I've modified the template so that everyone can rebuild the RDK lab at home.
=> RDK Workshop local build

rdk/template/configManagedRule.json, rdk/template/configManagedRuleWithRemediation.json
=> fix configManagedRule deployment

rdk/__init__.py, rdk/rdk.py
=> RELEASE 0.7.7 Feature/Export custom rule to terraform file

rdk/template/example_ci/AWS_CloudFormation_Stack.json
Example CloudFormation Stack CI does not exist.
Adding example CI for a CloudFormation Stack.
=> adding example cloudformation stack ci

requirements-dev.txt
Adding `sphinx-argparse` to local development requirements
=> Add sphinx-argparse to local dev requirements

rdk/__init__.py
1. Add skipping code bucket creation option for 'rdk init' with --skip-code-bucket-creation and using --custom-code-bucket for 'rdk deploy' with existing bucket
2. introduce beta feature for create SSM document (https://github.com/awslabs/aws-config-rdk/pull/210)
3. update accepted_resource_types (add AWS::SNS::Topic and AWS::SQS::Queue)
4. Add sphinx-argparse to local dev requirements (https://github.com/awslabs/aws-config-rdk/pull/243)
5. adding example cloudformation stack ci(https://github.com/awslabs/aws-config-rdk/pull/252)
=> RELEASE 0.7.8

MANIFEST.in, README.rst, docs/getting_started.rst, rdk/__init__.py, rdk/rdk.py, rdk/template/runtime/python3.8/rule_code.py, rdk/template/runtime/python3.8/rule_test.py, testing/linux-python3-buildspec.yaml, testing/test_windows.sh
Issue: #268 
Description of changes: Add Python 3.8 as valid runtime.
=> Add support for Python 3.8

MANIFEST.in, README.rst, docs/getting_started.rst, rdk/__init__.py, rdk/rdk.py, rdk/template/runtime/python3.8/rule_code.py, rdk/template/runtime/python3.8/rule_test.py, testing/linux-python3-buildspec.yaml, testing/test_windows.sh
RELEASE 0.7.11
1. Add support for Python 3.8 (https://github.com/awslabs/aws-config-rdk/pull/269)
=> RELEASE 0.7.11

MANIFEST.in, docs/reference/deploy.rst, docs/reference/export.rst, rdk/rdk.py, rdk/template/configRule.json, rdk/template/terraform/0.11/config_rule.tf, rdk/template/terraform/0.11/variables.tf, rdk/template/terraform/0.12/config_rule.tf, rdk/template/terraform/0.12/variables.tf
Add new parameter to control the lambda function timeout (#254)
=> Add support for custom lambda function timeout

rdk/template/configManagedRule.json, rdk/template/configManagedRuleWithRemediation.json
*Issue #, if available:* [#310](https://github.com/awslabs/aws-config-rdk/issues/310)
As discussed in the issue, this template change should fix the error shown when deploying managed rules.
PR to modify configManagedRule.json and configManagedRuleWithRemediation.json
=> Add [RuleLamdaName] parameter to configManagedRule.json

MANIFEST.in, README.rst, rdk/__init__.py, rdk/rdk.py, rdk/template/runtime/python3.9-lib/rule_code.py, rdk/template/runtime/python3.9-lib/rule_test.py, rdk/template/runtime/python3.9/rule_code.py, rdk/template/runtime/python3.9/rule_test.py, testing/linux-python3-buildspec.yaml, testing/test_windows.sh
1) Added support for Python 3.9 and Python 3.9 RDKlib runtimes.
2) Added AWS::Kinesis and AWS::Backup to accepted resource types list.
3) Updated documentation to include Python 3.9 and fixed minor typos.
Thank you for @AndersonLovelace and @tekdj7.
=> RELEASE 0.8.2

setup.py
*Issue #, if available:* N/A
*Description of changes:* Add PyYaml as a dependency.
=> add pyyaml dependency to setup

rdk/rdk.py, test-region.yaml
**Description of changes:**
Fixed build issues that were due to the combining of the opt-in and default regions
=> Separated opt-in and default regions

testing/multi_region_execution_test.py
Fixing test file for new regions
=> Fixed test file

README.rst, rdk/rdk.py, rdk/template/example_ci/AWS_IAM_Role.json
Updated SLR from AWSConfigRole to AWS_ConfigRole
=> Updated IAM Role to new

README.rst
=> hotfix on readme format

README.rst, rdk/__init__.py, testing/windows-python3-buildspec.yaml
Changes :
1.  resolved https://github.com/awslabs/aws-config-rdk/issues/352
2. upodate Newtonsoft.Json version
=> RELEASE 0.8.5

rdk/rdk.py
*Issue #, if available:* #362
*Description of changes:*  The purpose of this PR is to address the absent python3.9 support entries throughout the rdk.py file.
=> Add missing python 3.9 entries to rdk.py

testing/linux-python3-buildspec.yaml, testing/windows-python3-buildspec.yaml
*Issue #, if available:* n/a
*Description of changes:* The goal of this PR is to resolve CI build issues resulting from 3.6 and 3.9 routine changes.
=> Adjust buildspecs for py39

rdk/__init__.py
* Update rdk.py by @ivanfuglo in https://github.com/awslabs/aws-config-rdk/pull/353
* Bump Newtonsoft.Json from 10.0.1 to 13.0.1 in /rdk/template/runtime/dotnetcore1.0 by @dependabot in https://github.com/awslabs/aws-config-rdk/pull/351
* Bump Newtonsoft.Json from 10.0.1 to 13.0.1 in /rdk/template/runtime/dotnetcore2.0 by @dependabot in https://github.com/awslabs/aws-config-rdk/pull/350
* Adjust buildspecs for py39 in https://github.com/awslabs/aws-config-rdk/pull/372
* Remove unused import and six usage for 2.x support in https://github.com/awslabs/aws-config-rdk/pull/371
* Add missing python 3.9 entries to rdk.py in https://github.com/awslabs/aws-config-rdk/pull/368
* Remove python supported version copy in https://github.com/awslabs/aws-config-rdk/pull/367
* Remove 3.6 support in …
=> RELEASE 0.9.0

pyproject.toml
*Issue #, if available:* #384
*Description of changes:* The purpose of this PR is to update the `rdk` package meta to include the docs page.
=> Add documentation url to package meta

README.rst
*Issue #, if available:* n/a
*Description of changes:* The purpose of this PR is to update the maintainers / contributors list to reflect current maintainers.
=> Update the current maintainers of the project

pyproject.toml, rdk/__init__.py
due to https://github.com/awslabs/aws-config-rdk/pull/394
=> version bump for 0.12.0

README.rst
*Description of changes:*  The goal of this PR is to add PyPi and download badges to the repo readme.
=> Add badges to repo

rdk-workshop/instructions.md, rdk/template/runtime/nodejs4.3/rule_code.js, rdk/template/runtime/nodejs6.10/rule_code.js, rdk/template/runtime/python3.7/rule_code.py, rdk/template/runtime/python3.8/rule_code.py, rdk/template/runtime/python3.9/rule_code.py
- Fixing a few of the typos currently shown on the templates generated and in the README.
=> fix: Typos across the templates

README.rst
*Issue #, if available:* N/A
*Description of changes:* The goal of this PR is to introduce a notice to this repository elaborating on the support of this project.
=> Add support notice

.readthedocs.yaml, .readthedocs.yaml.off, developer_notes.md, pyproject.toml, rdk/__init__.py
N/A
Changes to release minor version 0.16.0
=> Add 0.16.0 changes

pyproject.toml, rdk/__init__.py, rdk/template/runtime/python3.11-lib/rule_code.py, rdk/template/runtime/python3.11-lib/rule_test.py, rdk/template/runtime/python3.11/rule_code.py, rdk/template/runtime/python3.11/rule_test.py
#456 
Runtime folder hadn't been added for Python 3.11 -- this adds it
=> add template for py311

rdk/template/example_ci/AWS_IAM_User.json
Fixed incorrect field name in example CI.
=> Correct field name in example CI

developer_notes.md, rdk/rdk.py
#118 
If STS check fails, print a user-friendly error message.
And a few documentation updates
=> Clearer error message if not authenticated

rdk/rdk.py
#491 
See details in issue linked above. Fixes incorrect Boolean logic in the evaluation of the Lambda Layer check.
=> bugfix-handle-lambda-layers-better

README.md, pyproject.toml, rdk/rdk.py, testing/linux-python3-buildspec.yaml, testing/windows-python3-buildspec.yaml
=> Add python 3.12 support

rdk/template/example_ci/AWS_Glue_Job.json
Closes #516 
Adds a basic Glue Job CI for testing/validation.
=> add-glue-job-ci

rdk/template/example_ci/AWS_Glue_Classifier.json, rdk/template/example_ci/AWS_Glue_MLTransform.json
#518 
Adds two new Glue example CIs
=> Add new glue CIs

pyproject.toml, rdk/__init__.py, rdk/template/configRule.yaml
Closes #522 
Use pseudoparameter for Partition instead of "aws"
=> fix partition hardcode

pyproject.toml, rdk/__init__.py, rdk/template/configRule.yaml
Need to use the !Sub function so that partition isn't treated as a string.
=> Apply sub function to partition
