rdk/rdk.py

Simplify permission management when cross account is enabled.

Add ReadOnly to Config Role

---

rdk/rdk.py

fix for issue #61 
also moved `rule_names = self.__get_rule_list_for_command()` to beginning inorder to validate the argument before creating the boto3 session.

Fix for "deploy" command doesn't display usage instructions when run with no args

---

rdk/rdk.py

When using the create-rule-template command, RDK now automatically creates CFN Parameters that map to the Config input parameters for each Rule.  Also adds the concept of "Optional Parameters" that control how the CFN parameters are constrained and applied to the Config Rule resources.

Pass Config Parameters through to generated CFN Templates

---

rdk/rdk.py

Got function failing because of 1 minute timeout, in large deployment.

Extend timeout for lambda

---

rdk/rdk.py

seems to be an extra comma in 'AWS::DynamoDB::Table' resourcetype, removed it

typofix in dynamodb::table resource_type

---

bin/rdk.cmd
setup.py

[windows] issue #80 
this wrapper allows to run rdk in any directory without using the full path of rdk file.
++ typing `rdk` command in any directory should execute rdk

batchfile wrapper for rdk

---

README.rst
rdk/rdk.py
rdk/template/configManagedRule.json

- Add the ability to deploy rules which are not Custom, allowing to centralize the management of the Rules (Custom and Managed) then deploy them through the same pipeline/command.
- Remove empty parameters value from OptionalParameters, since they are optional. Keeping track of the parameters in the parameters.json is practical.
- Update the copyright to 2019
Fix #124

New feature to deploy AWS Managed Rules with RDK

---

rdk/rdk.py
rdk/template/example_ci/AWS_SSM_ManagedInstanceInventory_Windows.json

https://github.com/awslabs/aws-config-rdk/issues/156
[fix] - sample-ci for *AWS::SSM::ManagedInstanceInventory::Windows* json  
_[in-progress] - sample-ci for AWS::SSM::ManagedInstanceInventory::Linux
Redesign for sample-ci option, that accepts an optional flag_
`[--distro=Windows,Centos,AmazonLinux ... ].`
`rdk sample-ci AWS::SSM::ManagedInstanceInventory::Windows`

Improper sample-ci json found

---

rdk/rdk.py

*Issue #169:*
Added the tags returned by the `def __create_function_cloudformation_template(self):` call to the cloud-formation template generated for the lambda template(s).

#169 - Fix for tagging lambda functions created by RDK

---

rdk/template/runtime/python3.7/rule_code.py
rdk/template/runtime/python3.7/rule_test.py

sync out of date python3.7 rule_code.py and rule_test.py templates with 3.6 so that rules can pass pylint out of the box

sync out of date python3.7 rule_code.py and rule_test.py templates w/3.6

---

docs/reference/create-rule-template.rst
docs/reference/deploy.rst
rdk/rdk.py
rdk/template/configRule.json

Create new deployment option for specifying custom rules lambda function role
Adding a new flag, --lambda-role-arn, for "rdk deploy" command. This option will take the parameter IAM role ARN and attach it to all the custom rules lambda functions and deploy them to the associated account. This is very important for some infrastructure that requires highly secured IAM policies with minimized permission. With this feature, User can define their own policy/role and take full control of what permissions will be granted. 

Add lambda role flag

---

rdk/rdk.py

To enable the use of RDKLib, source runtime should be set as python3.6-lib in parameter.json. However, when we do "rdk deploy -f", it is not modified to be "python3.6" for lambda function setting in cloudformation. 

fix lambda function runtime for rdklib implementation

---

docs/reference/deploy.rst
rdk/__init__.py
rdk/rdk.py
rdk/template/configRule.json

For security purpose, all lambda functions should be created within VPC. Adding ability to provide VPC information to RDK lambda cloudformation template. 

[NEW FEATURE] Create RDK Lambda functions within VPC

---

docs/conf.py
rdk/rdk.py
requirements-dev.txt

resolves: #224 #225 #226 #229
relates to: #218 
In regards to #218, this is workaround because the documentation on ReadTheDocs is pointing at a different repo
Previously there were multiple bugs within the `rdk` that meant `modify` wasn't respecting previously created rules `parameters.json`. I have also included numerous other fixes around the `rdk` when using it to generate the CloudFormation for multi-account deployments.
These issues have been fixed by:
* Removing `--remediation-resource-id-parameter` This flag did nothing
* Changing how `remediation_parameters` was calculated. Previously if you didn't set these on `create`, `Parameters` wouldn't show up in the JSON file, this was expected behaviour. If you then ran `modify` the …

Fix issues within RDK deploy & remediation

---

.gitignore
rdk/rdk.py

N/A, Emailed Michael with Suggestion, from:Liam.wadman@gmail.com
enabled --verbose for "test-local" to allow stdout from code to be printed. This is exceptionally useful for debugging when developing with RDK.

Added Verbose functionality for test-local

---

docs/reference/create-rule-template.rst
rdk/__init__.py
rdk/rdk.py

1. "rdk deploy" now support tagging config rules. 
2. "rdk create-rule-template" now generates a script for user to execute in order to create tags for each config rule. In addition, You can output the script in file with "-t | --tag-config-rules-script <file path>"
*Cloudformation is not supporting tagging config rule resources at the moment. 

REALEASE 0.7.5 Add tags to 'deploy' config rule and generate script for adding config rule tags on 'create-rule-template'

---

docs/reference/export.rst
rdk/rdk.py
rdk/template/terraform/0.11/config_rule.tf
rdk/template/terraform/0.11/variables.tf
rdk/template/terraform/0.12/config_rule.tf
rdk/template/terraform/0.12/variables.tf

This PR adds the new command "export", to export the custom rule to terraform file. 
Here is a sample command to export the rule:
>>**rdk export  << rule-name >>  -f terraform -v 0.12**
It generates the three .tf files in the current directory.
- << rule-name >>_custom_rule.tf : terraform script, that upload the rule to S3, deploy the lambda, create the aws config rule and required IAM roles/policies.
- << rule-name >>_variables.tf: Varabiles definitions.
- << rule-name >>.tfvars.json: Variable values.
Then use the below terraform command to deploy the rule.
**>>terraform  apply  -var-file="<< rule-name >>.tfvars.json"  --var source_bucket=<< existing s3 bucket name >>**
Use the below command to get help of this new command.
> **rdk export -h**
> usage: rdk export [-h] [-s RULESETS] …

Feature/Export custom rule to terraform file.

---

rdk/rdk.py
rdk/template/configManagedRule.json
rdk/template/configManagedRuleWithRemediation.json
rdk/template/configRule.json

*Issue  https://github.com/awslabs/aws-config-rdk/issues/96*
* Add "Description" parameter to the cloudformation templates.
* Add "Description" parameter into **parameters.json**
* Use the new "Description" parameter from **parameters.json** in the cloudformation template.

Add rule description into rule parameters

---

rdk/rdk.py
rdk/template/configRule.json

Allow deployers to specify a --boundary-policy-arn, which gets injected into the generated AWS::IAM::Role, as [PermissionsBoundary](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-permissionsboundary). 
#264

Implements a --boundary-policy-arn argument for `rdk deploy`

---

rdk/rdk.py

*Issue #, if available:* N/A
This change will allow you to manually set the value of `SourceHandler` which is used for the Lambda Function `Handler` property.
My use-case for this is a naming convention where hyphens are used in the Config rule names, but Python not liking hyphens in file names. Without this change, you are forced to use underscores instead of hyphens. With this change, you are free to name your rule whatever you want, and override the auto-generated value of `SourceHandler`.
This change is 100% backwards compatible and will not break any existing behaviour.

Adding 'SourceHandler' parameter

---

rdk/rdk.py

*Issue #, if available:* UNKNOWN
*Description of changes:* According to AWS docs, config rule names may have up to 128 characters. This PR changes the constants that RDK places on rule names (https://docs.aws.amazon.com/config/latest/APIReference/API_ConfigRule.html)

Config rule names may have up to 128 characters

---

README.rst

**Issue #, if available:**
none
**Description of changes:**
In the root **README** of this repo, `rdk init` command is a bit ambiguous for **multi-account/control-tower** users as it doesn't provide full information at first look. You have to dig in the previous issues/PRs to find the fact that additional arguments have to be provided for config-rdk installation which is only a waste of time.
So, I have just added those additional arguments in the readme to avoid the caused hassle.

Update README for Cross Account additional arguments.

---

rdk/template/runtime/python3.6-lib/rule_test.py
rdk/template/runtime/python3.6/rule_test.py
rdk/template/runtime/python3.7/rule_test.py
rdk/template/runtime/python3.8/rule_test.py

The unittest package has included mock since Python 3.3. These changes update the Python 3.6, 3.6-lib, 3.7, and 3.8 templates to default to unittest.mock instead of trying to import mock.

Update Python 3 runtime templates to use unittest.mock

---

README.rst
rdk/rdk.py
rdk/template/configManagedRuleOrganization.json

- Added support for Managed Rules deployment via 'deploy-organization' command
- Removed Lambda parameter reference in Managed rule templates for Org rules
- Created a Org Rule template for managed rules deployment

Managed Rule Deployment Support for Organization Command

---

MANIFEST.in
README.rst
rdk/__init__.py
rdk/rdk.py
rdk/template/runtime/python3.9-lib/rule_code.py
rdk/template/runtime/python3.9-lib/rule_test.py
rdk/template/runtime/python3.9/rule_code.py
rdk/template/runtime/python3.9/rule_test.py
testing/linux-python3-buildspec.yaml
testing/test_windows.sh

* No Issue numbers
* Added support for Python 3.9 and Python 3.9 RDKlib runtimes.
* Added AWS::Kinesis and AWS::Backup to accepted resource types list.
* Updated documentation to include Python 3.9 and fixed minor typos.
* Updated Python buildspec file to include Python 3.9 tests.

Add support for Python 3.9 Lambda runtimes

---

rdk/template/configRule.json
rdk/template/configRuleOrganization.json

133
Adding OversizedConfigurationItemChangeNotification as another message type because it's required to be sure that all notifications are handled.

Fix to issue 133 - add OversizedConfigurationItemChangeNotification by default

---

rdk/cli.py

*Issue #, if available:* #370
*Description of changes:* The purpose of this PR is to remove `six` usage previously intended to support python 2 <> 3 for import handling.

Remove unused import and six usage for 2.x support

---

pyproject.toml

*Description of changes:*  The purpose of this PR is to adjust the package name to conform to the setup.py package name: `rdk`

Fix package name to conform to the current module

---

docs/conf.py
docs/requirements.txt

*Issue #, if available:* #386
*Description of changes:* The goal of this PR is to resolve the RTD build failures (similar to here:  https://readthedocs.org/projects/aws-config-rdk/builds/19116212/)  -- the encountered failure is described here:  https://github.com/readthedocs/readthedocs.org/issues/9037

Adjust the RTD dependencies for old sphinx version

---

README.md

*Issue #, if available:* N/A
*Description of changes:* The goal of this PR is to ensure we have alignment in the documentation endpoints we are communicating.  rdk.readthedocs will soon be an alias to the new docs, but currently isn't.

Update RTD url in README

---

rdk/rdk.py

In the absence of using Control Tower, `rdk init` will try to overwrite the configuration recorder even when there is one. recording All resource types might not be efficient for all environments.
Initialization method of rdk updated to prevent the `put_configuration_recorder` API call when there is a configuration recorder available in AWS Config. 

rdk init: only put the configuration recorder if it's not exist

---

rdk/template/runtime/python3.10-lib/rule_test.py
rdk/template/runtime/python3.11-lib/rule_test.py
rdk/template/runtime/python3.7-lib/rule_test.py
rdk/template/runtime/python3.8-lib/rule_test.py
rdk/template/runtime/python3.9-lib/rule_test.py

Removes an accidental change where rdklib unit test templates had a hardcoded value

remove hardcoded rule name from rdklib unit tests
